#!/bin/sh

export PS4=' $SECONDS + '
date
set -x

export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
[[ -d $DATA ]] && rm -rf $DATA
mkdir -p $DATA
cd $DATA

mkdir -p $DATA/parm/models

export SENDECF=YES
export NET=runhistory
export RUN=runhistory

if [ ${envir} = "prod" ]
then
    export HPSSOUT=${HPSSOUT:-/NCEPPROD/hpssprod/runhistory}
    export HPSSOUT_OBS=${HPSSOUT_OBS:-/NCEPOBSERV/hpssprod/runhistory}
else
    export HPSSOUT=${HPSSOUT:-/NCEPPROD/hpsspara/runhistory/ops.para}
    export HPSSOUT_OBS=${HPSSOUT_OBS:-/NCEPOBSERV/hpsspara/runhistory/ops.para}
fi

# Set TMPDIR, which is needed by htar
export TMPDIR=$DATA

export cycle=t${cyc}z
export CYCLE=T${cyc}Z

setpdy.sh 10
. ./PDY

export outid="LL$job"
export pgmout="OUTPUT.${pid}"

export USHrunhistory=${USHrunhistory:-$HOMErunhistory/ush}
export PARMrunhistory=${PARMrunhistory:-$DATA/parm}
export PARMrunhistory_fixed=${PARMrunhistory_fixed:-$HOMErunhistory/parm}
export LOGrunhistory=${LOGrunhistory:-$(compath.py -v ${envir}/${NET}/${runhistory_ver})/${RUN}}
mkdir -p $LOGrunhistory

env

#############################################################
${HOMErunhistory}/scripts/exrhist.sh
#############################################################
date
cd $DATAROOT
if [ "$KEEPDATA" != YES ]; then rm -rf $DATA; fi
